[package]
name = "gelfgren-r"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
gelfgren-core = { path = "../../../../gelfgren-core" }
extendr-api = "0.7"

[build-dependencies]
extendr-api = "0.7"
